# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'LSNetworking' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LSNetworking
  pod 'LSNetworking', :path => '../'
  pod 'TTLog', '~> 0.2.0'
end
